namn=input("vad heter du?")
print(namn, "är ett fint namn.")
favoritmat = input("vilken mat gillar du?")
print(namn, favoritmat, "är verkligen gott.")
pengar = input("hur mycket pengar har du i fickan?")
